[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
prog1 = "2FRKbweUTZrUQEjLoPaDbA7nznbvP5jw7UtNhRQNKX1K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
